### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to protected method shoppingCart::generate_cart_id() from ...class.savecart.php on line 142

### ISSUE THREAD

**Issue by torvista** [lat9/keep_cart#3]
I was testing this by deleting the zenid when not logged in.
On the subsequent page load, this debug was generated.
I'm not sure if it is irrelevant or indicating that the zenid is being created after this plugin code / there is some other issue.

**Comment by lat9** [comment]
Nope, it's indicating that zc158 somehow decided that the function is now protected.  I'll open a zc158 issue on GitHub ... although I'm now wondering how many other previously-public functions have also been pulled into protected status.

**Comment by lat9** [comment]
Thanks for the report @torvista; I've submitted a zc158 PR to put Humpty Dumpty back together again.

**Comment by torvista** [comment]
Fixed by;https://github.com/zencart/zencart/pull/4682
