### ISSUE TITLE
Using unserialize

### ISSUE THREAD

**Issue by torvista** [lat9/keep_cart#4]
From what I read it is the work of the devil's and to be avoided if at all possible.
Is it still the best solution to the storage of the cart?

**Comment by lat9** [comment]
Storing a cart's contents is not like storing credit-cart ro password information.  Any changes to the means of 'encoding' (or squishing) the data for the associated cookie would result in unrestored customers' carts if the cart was saved using a different encoding method.

**Comment by torvista** [comment]
Ok, I was just reading that unserializing external (hence tainted) data was to be avoided if at all possible.
